### PR TITLE
Testing environment setup

### PR DESCRIPTION
**Pull request by SxThx**
added mocha and chai dependencies

### CODE REVIEW

**Review by 0nyxxxx — APPROVED** [review]
Looks good

**Review by 0nyxxxx — DISMISSED** [review]
changes look good

**Review by Chromacry — CHANGES_REQUESTED** [review]
I have taken a look at your changes.
Please install the following package as well for code coverage.

>$ npm install nyc

**Review by Chromacry — APPROVED** [review]
looks good

**Pull request merged**
